#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

cat <<EOL > /etc/nginx/sites-available/temporary_redirect
server {
    listen 80 default_server;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL

# Enable the temporary redirection configuration
if [ ! -e /etc/nginx/sites-enabled/temporary_redirect ]; 
then
    ln -s /etc/nginx/sites-available/temporary_redirect /etc/nginx/sites-enabled/
fi

sudo nginx -t && sudo service nginx reload

sudo rm /etc/nginx/sites-available/temporary_redirect
