#!/usr/bin/env bash
#Replicate web_01 to kickstart the load balancer tests

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s#server_name _;#$string_for_replacement#"  /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s#listen 80 default_server;#$string_for_replacement#" /etc/nginx/sites-enabled/default

string_for_addition="location / {\n\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "s#location / {#$string_for_addition#" /etc/nginx/sites-enabled/default

sudo service nginx restart
