#!/usr/bin/env bash
#Install and configure HAproxy on lb-01.

sudo apt update
sudo apt-get install -y haproxy

echo "
frontend http-front
	bind *:80
	mode http
	
	default_backend http-back
	
	

backend http-back
	balance roundrobin
	server web-01 100.25.4.209:80 check
	server web-02 54.146.64.38:80 check

" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haporoxy restart
