#!/usr/bin/env bash
# Display numbers 1-10 with some differences using while and if statements

i=1

while [ $i -le 10 ]
do

	if [ $i == 4 ] 
	then
		echo "bad luck"
	elif [ $i == 8 ] 
	then
		echo "good luck"
	else
		echo "Best School"
	fi
i=$(($i+1))
done
