#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes

h=0
m=1

echo "Hour: 0"
while true
do
	echo $m
	((m++))

	if [ "$m" -gt 59 ]
	then
		m=1
		((h++))
		echo "Hour: $h"
	fi

done
