#!/usr/bin/env bash
# This script gracefully reloads Gunicorn

# Find the Gunicorn master process ID (PID)
GUNICORN_PID=$(pgrep -f 'gunicorn: master')

# If gunicornn not already active then exit
if [ -z "$GUNICORN_PID" ]; then
    exit 1
fi

# Send the HUP signal to gracefully reload Gunicorn
kill -HUP "$GUNICORN_PID"